### PR TITLE
fix fields method incompatible params issue

### PR DESCRIPTION
**Pull request by tooshay**
Quick fix for Nova V4 compatibility issue.

### CODE REVIEW

**Comment by antonkomarev** [comment]
@tooshay thank you for the contribution! Is it backward compatible or we need to release major version?

**Comment by tooshay** [comment]
I'd go for a major release, @antonkomarev.

I haven’t tested it with Nova v3 (on a bit of a tight deadline atm). Judging from these changes though, as we’re changing this method signature from an overridden method, it likely isn’t backwards compatible as it will generate the following warning:

```WARNING Declaration of Ban::fields(NovaRequest $request) should be compatible with Action::fields() on line number 55```

**Comment by antonkomarev** [comment]
Merged. Will try to make a release ASAP.

**Comment by antonkomarev** [comment]
Fixes #12

**Comment by antonkomarev** [comment]
@tooshay Just released Laravel Nova Ban v2 with your MR. Thank you!

**Comment by Jamiewarb** [comment]
Ah awesome, thanks both

**Pull request merged**
